---
chdir: /home/oiv/Projects/resque-monitor
socket: /tmp/resque_monitor_production_thin.sock
log: /home/oiv/Projects/resque-monitor/log/resque_monitor_production_thin.log
pid: /home/oiv/Projects/resque-monitor/tmp/pids/resque_monitor_production_thin.pid
environment: production
daemonize: true
servers: 1
threaded: false
no-epoll: false
rackup: /home/oiv/Projects/resque-monitor/config.ru
